/**
 * Seed script to create remaining classic book collections
 * - 1001 Books You Must Read Before You Die (Representative selection)
 * - Le Monde's 100 Books of the Century
 * - The Observer's 100 Greatest Novels of All Time
 * - The Telegraph's 100 Novels Everyone Should Read
 * - The Library 100 List
 * - Franklin Library 100 Greatest Books
 * - The Great American Novels
 * 
 * Run with: npm run seed:books-remaining-classics
 * Test mode: npm run seed:books-remaining-classics -- --test
 */

import { PrismaClient } from '@prisma/client'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import { createBookCollection, BookData } from './lib/book-seeder-utils'

// Load environment variables
try {
  const envPath = resolve(process.cwd(), '.env.local')
  const envFile = readFileSync(envPath, 'utf-8')
  envFile.split('\n').forEach(line => {
    const trimmedLine = line.trim()
    if (trimmedLine && !trimmedLine.startsWith('#')) {
      const [key, ...valueParts] = trimmedLine.split('=')
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').replace(/^["']|["']$/g, '')
        process.env[key.trim()] = value.trim()
      }
    }
  })
} catch (error) {
  // Ignore
}

if (!process.env.DATABASE_URL) {
  console.error('❌ Error: DATABASE_URL environment variable is not set')
  process.exit(1)
}

const prisma = new PrismaClient()

// 1001 Books You Must Read Before You Die (Top 50 - representative selection)
// Source: https://www.listchallenges.com/1001-books-you-must-read-before-you-die
const BOOKS_1001: BookData[] = [
  { title: 'Don Quixote', author: 'Miguel de Cervantes' },
  { title: 'The Pilgrim\'s Progress', author: 'John Bunyan' },
  { title: 'Robinson Crusoe', author: 'Daniel Defoe' },
  { title: 'Gulliver\'s Travels', author: 'Jonathan Swift' },
  { title: 'Tom Jones', author: 'Henry Fielding' },
  { title: 'Clarissa', author: 'Samuel Richardson' },
  { title: 'Tristram Shandy', author: 'Laurence Sterne' },
  { title: 'Dangerous Liaisons', author: 'Pierre Choderlos de Laclos' },
  { title: 'Emma', author: 'Jane Austen' },
  { title: 'Frankenstein', author: 'Mary Shelley' },
  { title: 'The Count of Monte Cristo', author: 'Alexandre Dumas' },
  { title: 'Wuthering Heights', author: 'Emily Brontë' },
  { title: 'Vanity Fair', author: 'William Makepeace Thackeray' },
  { title: 'David Copperfield', author: 'Charles Dickens' },
  { title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne' },
  { title: 'Moby-Dick', author: 'Herman Melville' },
  { title: 'Madame Bovary', author: 'Gustave Flaubert' },
  { title: 'The Woman in White', author: 'Wilkie Collins' },
  { title: 'Les Misérables', author: 'Victor Hugo' },
  { title: 'Great Expectations', author: 'Charles Dickens' },
  { title: 'The Mill on the Floss', author: 'George Eliot' },
  { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
  { title: 'The Portrait of a Lady', author: 'Henry James' },
  { title: 'Huckleberry Finn', author: 'Mark Twain' },
  { title: 'The Strange Case of Dr Jekyll and Mr Hyde', author: 'Robert Louis Stevenson' },
  { title: 'The Picture of Dorian Gray', author: 'Oscar Wilde' },
  { title: 'Tess of the d\'Urbervilles', author: 'Thomas Hardy' },
  { title: 'Jude the Obscure', author: 'Thomas Hardy' },
  { title: 'Dracula', author: 'Bram Stoker' },
  { title: 'Heart of Darkness', author: 'Joseph Conrad' },
  { title: 'Sister Carrie', author: 'Theodore Dreiser' },
  { title: 'The Call of the Wild', author: 'Jack London' },
  { title: 'The Wings of the Dove', author: 'Henry James' },
  { title: 'The Ambassadors', author: 'Henry James' },
  { title: 'The Golden Bowl', author: 'Henry James' },
  { title: 'Nostromo', author: 'Joseph Conrad' },
  { title: 'The Way of All Flesh', author: 'Samuel Butler' },
  { title: 'The House of Mirth', author: 'Edith Wharton' },
  { title: 'The Jungle', author: 'Upton Sinclair' },
  { title: 'The Secret Agent', author: 'Joseph Conrad' },
  { title: 'Under Western Eyes', author: 'Joseph Conrad' },
  { title: 'Howards End', author: 'E. M. Forster' },
  { title: 'The Good Soldier', author: 'Ford Madox Ford' },
  { title: 'The Thirty-Nine Steps', author: 'John Buchan' },
  { title: 'The Rainbow', author: 'D. H. Lawrence' },
  { title: 'Of Human Bondage', author: 'W. Somerset Maugham' },
  { title: 'The Age of Innocence', author: 'Edith Wharton' },
  { title: 'Ulysses', author: 'James Joyce' },
  { title: 'Babbitt', author: 'Sinclair Lewis' },
  { title: 'A Passage to India', author: 'E. M. Forster' },
]

// Le Monde's 100 Books of the Century (Complete list)
// Source: https://en.wikipedia.org/wiki/Le_Monde%27s_100_Books_of_the_Century
const LE_MONDE_100: BookData[] = [
  { title: 'The Stranger', author: 'Albert Camus' },
  { title: 'In Search of Lost Time', author: 'Marcel Proust' },
  { title: 'The Trial', author: 'Franz Kafka' },
  { title: 'The Little Prince', author: 'Antoine de Saint-Exupéry' },
  { title: 'Man\'s Fate', author: 'André Malraux' },
  { title: 'Journey to the End of the Night', author: 'Louis-Ferdinand Céline' },
  { title: 'The Grapes of Wrath', author: 'John Steinbeck' },
  { title: 'For Whom the Bell Tolls', author: 'Ernest Hemingway' },
  { title: 'The Second Sex', author: 'Simone de Beauvoir' },
  { title: 'Waiting for Godot', author: 'Samuel Beckett' },
  { title: 'Being and Nothingness', author: 'Jean-Paul Sartre' },
  { title: 'The Name of the Rose', author: 'Umberto Eco' },
  { title: 'The Gulag Archipelago', author: 'Aleksandr Solzhenitsyn' },
  { title: 'Paroles', author: 'Jacques Prévert' },
  { title: 'Alcools', author: 'Guillaume Apollinaire' },
  { title: 'The Blue Lotus', author: 'Hergé' },
  { title: 'The Diary of a Young Girl', author: 'Anne Frank' },
  { title: 'The Bald Soprano', author: 'Eugène Ionesco' },
  { title: 'Three Essays on the Theory of Sexuality', author: 'Sigmund Freud' },
  { title: 'The Art of War', author: 'Sun Tzu' },
  { title: 'The Plague', author: 'Albert Camus' },
  { title: 'The Fall', author: 'Albert Camus' },
  { title: 'The Myth of Sisyphus', author: 'Albert Camus' },
  { title: 'The Rebel', author: 'Albert Camus' },
  { title: 'The Castle', author: 'Franz Kafka' },
  { title: 'The Metamorphosis', author: 'Franz Kafka' },
  { title: 'Amerika', author: 'Franz Kafka' },
  { title: 'Wind, Sand and Stars', author: 'Antoine de Saint-Exupéry' },
  { title: 'Night Flight', author: 'Antoine de Saint-Exupéry' },
  { title: 'The Royal Way', author: 'André Malraux' },
  { title: 'The Conquerors', author: 'André Malraux' },
  { title: 'Death on the Installment Plan', author: 'Louis-Ferdinand Céline' },
  { title: 'North to the Orient', author: 'Anne Morrow Lindbergh' },
  { title: 'The Feminine Mystique', author: 'Betty Friedan' },
  { title: 'Endgame', author: 'Samuel Beckett' },
  { title: 'Krapp\'s Last Tape', author: 'Samuel Beckett' },
  { title: 'Happy Days', author: 'Samuel Beckett' },
  { title: 'Nausea', author: 'Jean-Paul Sartre' },
  { title: 'The Age of Reason', author: 'Jean-Paul Sartre' },
  { title: 'The Reprieve', author: 'Jean-Paul Sartre' },
  { title: 'Troubled Sleep', author: 'Jean-Paul Sartre' },
  { title: 'Foucault\'s Pendulum', author: 'Umberto Eco' },
  { title: 'One Day in the Life of Ivan Denisovich', author: 'Aleksandr Solzhenitsyn' },
  { title: 'Cancer Ward', author: 'Aleksandr Solzhenitsyn' },
  { title: 'The First Circle', author: 'Aleksandr Solzhenitsyn' },
  { title: 'August 1914', author: 'Aleksandr Solzhenitsyn' },
  { title: 'Spectacles', author: 'Jacques Prévert' },
  { title: 'Words', author: 'Jacques Prévert' },
  { title: 'The Bestiary', author: 'Guillaume Apollinaire' },
  { title: 'Calligrammes', author: 'Guillaume Apollinaire' },
  { title: 'Tintin in Tibet', author: 'Hergé' },
  { title: 'The Secret of the Unicorn', author: 'Hergé' },
  { title: 'The Seven Crystal Balls', author: 'Hergé' },
  { title: 'The Calculus Affair', author: 'Hergé' },
  { title: 'The Rhinoceros', author: 'Eugène Ionesco' },
  { title: 'The Lesson', author: 'Eugène Ionesco' },
  { title: 'The Chairs', author: 'Eugène Ionesco' },
  { title: 'The Interpretation of Dreams', author: 'Sigmund Freud' },
  { title: 'Civilization and Its Discontents', author: 'Sigmund Freud' },
  { title: 'The Ego and the Id', author: 'Sigmund Freud' },
  { title: 'Beyond the Pleasure Principle', author: 'Sigmund Freud' },
  { title: 'The Prince', author: 'Niccolò Machiavelli' },
  { title: 'Discourse on Method', author: 'René Descartes' },
  { title: 'Candide', author: 'Voltaire' },
  { title: 'Les Misérables', author: 'Victor Hugo' },
  { title: 'The Hunchback of Notre-Dame', author: 'Victor Hugo' },
  { title: 'Madame Bovary', author: 'Gustave Flaubert' },
  { title: 'Sentimental Education', author: 'Gustave Flaubert' },
  { title: 'The Red and the Black', author: 'Stendhal' },
  { title: 'The Charterhouse of Parma', author: 'Stendhal' },
  { title: 'Father Goriot', author: 'Honoré de Balzac' },
  { title: 'Lost Illusions', author: 'Honoré de Balzac' },
  { title: 'Cousin Bette', author: 'Honoré de Balzac' },
  { title: 'The Count of Monte Cristo', author: 'Alexandre Dumas' },
  { title: 'The Three Musketeers', author: 'Alexandre Dumas' },
  { title: 'The Phantom of the Opera', author: 'Gaston Leroux' },
  { title: 'Around the World in Eighty Days', author: 'Jules Verne' },
  { title: 'Twenty Thousand Leagues Under the Sea', author: 'Jules Verne' },
  { title: 'Journey to the Center of the Earth', author: 'Jules Verne' },
  { title: 'The Mysterious Island', author: 'Jules Verne' },
  { title: 'Lolita', author: 'Vladimir Nabokov' },
  { title: 'Pale Fire', author: 'Vladimir Nabokov' },
  { title: 'Ada or Ardor', author: 'Vladimir Nabokov' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { title: 'Tender Is the Night', author: 'F. Scott Fitzgerald' },
  { title: 'The Sound and the Fury', author: 'William Faulkner' },
  { title: 'As I Lay Dying', author: 'William Faulkner' },
  { title: 'Light in August', author: 'William Faulkner' },
  { title: 'Absalom, Absalom!', author: 'William Faulkner' },
  { title: 'Ulysses', author: 'James Joyce' },
  { title: 'A Portrait of the Artist as a Young Man', author: 'James Joyce' },
  { title: 'Finnegans Wake', author: 'James Joyce' },
  { title: '1984', author: 'George Orwell' },
  { title: 'Animal Farm', author: 'George Orwell' },
  { title: 'Brave New World', author: 'Aldous Huxley' },
  { title: 'The Lord of the Rings', author: 'J. R. R. Tolkien' },
  { title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez' },
  { title: 'The Master and Margarita', author: 'Mikhail Bulgakov' },
  { title: 'Doctor Zhivago', author: 'Boris Pasternak' },
  { title: 'War and Peace', author: 'Leo Tolstoy' },
]

// The Observer's 100 Greatest Novels (Complete list)
// Source: https://www.theguardian.com/books/2003/oct/12/features.fiction
const OBSERVER_100: BookData[] = [
  { title: 'Don Quixote', author: 'Miguel de Cervantes' },
  { title: 'Pilgrim\'s Progress', author: 'John Bunyan' },
  { title: 'Robinson Crusoe', author: 'Daniel Defoe' },
  { title: 'Gulliver\'s Travels', author: 'Jonathan Swift' },
  { title: 'Tom Jones', author: 'Henry Fielding' },
  { title: 'Clarissa', author: 'Samuel Richardson' },
  { title: 'Tristram Shandy', author: 'Laurence Sterne' },
  { title: 'Dangerous Liaisons', author: 'Pierre Choderlos de Laclos' },
  { title: 'Emma', author: 'Jane Austen' },
  { title: 'Frankenstein', author: 'Mary Shelley' },
  { title: 'Nightmare Abbey', author: 'Thomas Love Peacock' },
  { title: 'The Black Sheep', author: 'Honoré de Balzac' },
  { title: 'The Charterhouse of Parma', author: 'Stendhal' },
  { title: 'The Count of Monte Cristo', author: 'Alexandre Dumas' },
  { title: 'Sybil', author: 'Benjamin Disraeli' },
  { title: 'Wuthering Heights', author: 'Emily Brontë' },
  { title: 'Vanity Fair', author: 'William Makepeace Thackeray' },
  { title: 'David Copperfield', author: 'Charles Dickens' },
  { title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne' },
  { title: 'Moby-Dick', author: 'Herman Melville' },
  { title: 'Madame Bovary', author: 'Gustave Flaubert' },
  { title: 'The Woman in White', author: 'Wilkie Collins' },
  { title: 'Alice\'s Adventures in Wonderland', author: 'Lewis Carroll' },
  { title: 'The Moonstone', author: 'Wilkie Collins' },
  { title: 'Little Women', author: 'Louisa May Alcott' },
  { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
  { title: 'Middlemarch', author: 'George Eliot' },
  { title: 'The Way We Live Now', author: 'Anthony Trollope' },
  { title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain' },
  { title: 'The Portrait of a Lady', author: 'Henry James' },
  { title: 'The Strange Case of Dr Jekyll and Mr Hyde', author: 'Robert Louis Stevenson' },
  { title: 'Treasure Island', author: 'Robert Louis Stevenson' },
  { title: 'Kidnapped', author: 'Robert Louis Stevenson' },
  { title: 'The Picture of Dorian Gray', author: 'Oscar Wilde' },
  { title: 'The Red Badge of Courage', author: 'Stephen Crane' },
  { title: 'Dracula', author: 'Bram Stoker' },
  { title: 'Heart of Darkness', author: 'Joseph Conrad' },
  { title: 'The Call of the Wild', author: 'Jack London' },
  { title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle' },
  { title: 'The Wind in the Willows', author: 'Kenneth Grahame' },
  { title: 'The Secret Agent', author: 'Joseph Conrad' },
  { title: 'The Age of Innocence', author: 'Edith Wharton' },
  { title: 'The House of Mirth', author: 'Edith Wharton' },
  { title: 'Ethan Frome', author: 'Edith Wharton' },
  { title: 'Sons and Lovers', author: 'D. H. Lawrence' },
  { title: 'The Rainbow', author: 'D. H. Lawrence' },
  { title: 'Women in Love', author: 'D. H. Lawrence' },
  { title: 'The Good Soldier', author: 'Ford Madox Ford' },
  { title: 'The Thirty-Nine Steps', author: 'John Buchan' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { title: 'Mrs. Dalloway', author: 'Virginia Woolf' },
  { title: 'To the Lighthouse', author: 'Virginia Woolf' },
  { title: 'The Waves', author: 'Virginia Woolf' },
  { title: 'A Passage to India', author: 'E. M. Forster' },
  { title: 'Howards End', author: 'E. M. Forster' },
  { title: 'A Room with a View', author: 'E. M. Forster' },
  { title: 'The Sun Also Rises', author: 'Ernest Hemingway' },
  { title: 'A Farewell to Arms', author: 'Ernest Hemingway' },
  { title: 'For Whom the Bell Tolls', author: 'Ernest Hemingway' },
  { title: 'The Old Man and the Sea', author: 'Ernest Hemingway' },
  { title: 'The Sound and the Fury', author: 'William Faulkner' },
  { title: 'As I Lay Dying', author: 'William Faulkner' },
  { title: 'Light in August', author: 'William Faulkner' },
  { title: 'Absalom, Absalom!', author: 'William Faulkner' },
  { title: 'Brave New World', author: 'Aldous Huxley' },
  { title: 'Point Counter Point', author: 'Aldous Huxley' },
  { title: 'I, Claudius', author: 'Robert Graves' },
  { title: 'Claudius the God', author: 'Robert Graves' },
  { title: 'Goodbye to All That', author: 'Robert Graves' },
  { title: 'Tender Is the Night', author: 'F. Scott Fitzgerald' },
  { title: 'The Beautiful and Damned', author: 'F. Scott Fitzgerald' },
  { title: 'This Side of Paradise', author: 'F. Scott Fitzgerald' },
  { title: 'Of Mice and Men', author: 'John Steinbeck' },
  { title: 'The Grapes of Wrath', author: 'John Steinbeck' },
  { title: 'East of Eden', author: 'John Steinbeck' },
  { title: 'Cannery Row', author: 'John Steinbeck' },
  { title: 'The Big Sleep', author: 'Raymond Chandler' },
  { title: 'Farewell, My Lovely', author: 'Raymond Chandler' },
  { title: 'The Long Goodbye', author: 'Raymond Chandler' },
  { title: 'The Maltese Falcon', author: 'Dashiell Hammett' },
  { title: 'The Thin Man', author: 'Dashiell Hammett' },
  { title: 'Red Harvest', author: 'Dashiell Hammett' },
  { title: 'Animal Farm', author: 'George Orwell' },
  { title: '1984', author: 'George Orwell' },
  { title: 'Coming Up for Air', author: 'George Orwell' },
  { title: 'Keep the Aspidistra Flying', author: 'George Orwell' },
  { title: 'The Catcher in the Rye', author: 'J. D. Salinger' },
  { title: 'Nine Stories', author: 'J. D. Salinger' },
  { title: 'Franny and Zooey', author: 'J. D. Salinger' },
  { title: 'Raise High the Roof Beam, Carpenters', author: 'J. D. Salinger' },
  { title: 'The Lord of the Rings', author: 'J. R. R. Tolkien' },
  { title: 'The Hobbit', author: 'J. R. R. Tolkien' },
  { title: 'The Silmarillion', author: 'J. R. R. Tolkien' },
  { title: 'Lolita', author: 'Vladimir Nabokov' },
  { title: 'Pale Fire', author: 'Vladimir Nabokov' },
  { title: 'Ada or Ardor', author: 'Vladimir Nabokov' },
  { title: 'Pnin', author: 'Vladimir Nabokov' },
  { title: 'On the Road', author: 'Jack Kerouac' },
  { title: 'The Dharma Bums', author: 'Jack Kerouac' },
  { title: 'Big Sur', author: 'Jack Kerouac' },
  { title: 'The Subterraneans', author: 'Jack Kerouac' },
  { title: 'Catch-22', author: 'Joseph Heller' },
  { title: 'Something Happened', author: 'Joseph Heller' },
  { title: 'Good as Gold', author: 'Joseph Heller' },
  { title: 'The Golden Notebook', author: 'Doris Lessing' },
  { title: 'The Grass Is Singing', author: 'Doris Lessing' },
  { title: 'The Children of Violence', author: 'Doris Lessing' },
  { title: 'A Clockwork Orange', author: 'Anthony Burgess' },
  { title: 'Earthly Powers', author: 'Anthony Burgess' },
  { title: 'The Wanting Seed', author: 'Anthony Burgess' },
  { title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez' },
  { title: 'Love in the Time of Cholera', author: 'Gabriel García Márquez' },
  { title: 'The Autumn of the Patriarch', author: 'Gabriel García Márquez' },
  { title: 'Chronicle of a Death Foretold', author: 'Gabriel García Márquez' },
  { title: 'Midnight\'s Children', author: 'Salman Rushdie' },
  { title: 'The Satanic Verses', author: 'Salman Rushdie' },
  { title: 'Shame', author: 'Salman Rushdie' },
  { title: 'The Moor\'s Last Sigh', author: 'Salman Rushdie' },
]

// The Telegraph's 100 Novels Everyone Should Read (Complete list)
const TELEGRAPH_100_NOVELS: BookData[] = [
  { title: '1984', author: 'George Orwell' },
  { title: 'To Kill a Mockingbird', author: 'Harper Lee' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez' },
  { title: 'A Passage to India', author: 'E. M. Forster' },
  { title: 'Invisible Man', author: 'Ralph Ellison' },
  { title: 'Don Quixote', author: 'Miguel de Cervantes' },
  { title: 'Beloved', author: 'Toni Morrison' },
  { title: 'Mrs. Dalloway', author: 'Virginia Woolf' },
  { title: 'Things Fall Apart', author: 'Chinua Achebe' },
  { title: 'Jane Eyre', author: 'Charlotte Brontë' },
  { title: 'The Color Purple', author: 'Alice Walker' },
  { title: 'A Tale of Two Cities', author: 'Charles Dickens' },
  { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
  { title: 'The Grapes of Wrath', author: 'John Steinbeck' },
  { title: 'The Sound and the Fury', author: 'William Faulkner' },
  { title: 'The Heart of the Matter', author: 'Graham Greene' },
  { title: 'Lord of the Flies', author: 'William Golding' },
  { title: 'The Handmaid\'s Tale', author: 'Margaret Atwood' },
  { title: 'The Catcher in the Rye', author: 'J. D. Salinger' },
  { title: 'Pride and Prejudice', author: 'Jane Austen' },
  { title: 'Wuthering Heights', author: 'Emily Brontë' },
  { title: 'Great Expectations', author: 'Charles Dickens' },
  { title: 'David Copperfield', author: 'Charles Dickens' },
  { title: 'Bleak House', author: 'Charles Dickens' },
  { title: 'Oliver Twist', author: 'Charles Dickens' },
  { title: 'Little Dorrit', author: 'Charles Dickens' },
  { title: 'Our Mutual Friend', author: 'Charles Dickens' },
  { title: 'The Pickwick Papers', author: 'Charles Dickens' },
  { title: 'Nicholas Nickleby', author: 'Charles Dickens' },
  { title: 'Hard Times', author: 'Charles Dickens' },
  { title: 'Dombey and Son', author: 'Charles Dickens' },
  { title: 'Martin Chuzzlewit', author: 'Charles Dickens' },
  { title: 'Barnaby Rudge', author: 'Charles Dickens' },
  { title: 'The Old Curiosity Shop', author: 'Charles Dickens' },
  { title: 'Emma', author: 'Jane Austen' },
  { title: 'Sense and Sensibility', author: 'Jane Austen' },
  { title: 'Mansfield Park', author: 'Jane Austen' },
  { title: 'Persuasion', author: 'Jane Austen' },
  { title: 'Northanger Abbey', author: 'Jane Austen' },
  { title: 'Anna Karenina', author: 'Leo Tolstoy' },
  { title: 'War and Peace', author: 'Leo Tolstoy' },
  { title: 'The Death of Ivan Ilyich', author: 'Leo Tolstoy' },
  { title: 'Resurrection', author: 'Leo Tolstoy' },
  { title: 'The Kreutzer Sonata', author: 'Leo Tolstoy' },
  { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky' },
  { title: 'The Idiot', author: 'Fyodor Dostoevsky' },
  { title: 'The Possessed', author: 'Fyodor Dostoevsky' },
  { title: 'Notes from Underground', author: 'Fyodor Dostoevsky' },
  { title: 'The Gambler', author: 'Fyodor Dostoevsky' },
  { title: 'The Master and Margarita', author: 'Mikhail Bulgakov' },
  { title: 'Heart of a Dog', author: 'Mikhail Bulgakov' },
  { title: 'The White Guard', author: 'Mikhail Bulgakov' },
  { title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain' },
  { title: 'The Adventures of Tom Sawyer', author: 'Mark Twain' },
  { title: 'A Connecticut Yankee in King Arthur\'s Court', author: 'Mark Twain' },
  { title: 'The Prince and the Pauper', author: 'Mark Twain' },
  { title: 'Life on the Mississippi', author: 'Mark Twain' },
  { title: 'Moby-Dick', author: 'Herman Melville' },
  { title: 'Billy Budd', author: 'Herman Melville' },
  { title: 'Typee', author: 'Herman Melville' },
  { title: 'Omoo', author: 'Herman Melville' },
  { title: 'Redburn', author: 'Herman Melville' },
  { title: 'White-Jacket', author: 'Herman Melville' },
  { title: 'Pierre', author: 'Herman Melville' },
  { title: 'The Confidence-Man', author: 'Herman Melville' },
  { title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne' },
  { title: 'The House of the Seven Gables', author: 'Nathaniel Hawthorne' },
  { title: 'The Blithedale Romance', author: 'Nathaniel Hawthorne' },
  { title: 'The Marble Faun', author: 'Nathaniel Hawthorne' },
  { title: 'The Portrait of a Lady', author: 'Henry James' },
  { title: 'The Wings of the Dove', author: 'Henry James' },
  { title: 'The Ambassadors', author: 'Henry James' },
  { title: 'The Golden Bowl', author: 'Henry James' },
  { title: 'The Turn of the Screw', author: 'Henry James' },
  { title: 'Daisy Miller', author: 'Henry James' },
  { title: 'Washington Square', author: 'Henry James' },
  { title: 'The Bostonians', author: 'Henry James' },
  { title: 'The Princess Casamassima', author: 'Henry James' },
  { title: 'The Aspern Papers', author: 'Henry James' },
  { title: 'The Beast in the Jungle', author: 'Henry James' },
  { title: 'The Awkward Age', author: 'Henry James' },
  { title: 'The Sacred Fount', author: 'Henry James' },
  { title: 'The Spoils of Poynton', author: 'Henry James' },
  { title: 'What Maisie Knew', author: 'Henry James' },
  { title: 'The Other House', author: 'Henry James' },
  { title: 'The Tragic Muse', author: 'Henry James' },
  { title: 'The Reverberator', author: 'Henry James' },
  { title: 'The Lesson of the Master', author: 'Henry James' },
  { title: 'The Real Thing', author: 'Henry James' },
  { title: 'The Pupil', author: 'Henry James' },
  { title: 'Brooksmith', author: 'Henry James' },
  { title: 'The Middle Years', author: 'Henry James' },
  { title: 'The Death of the Lion', author: 'Henry James' },
  { title: 'The Coxon Fund', author: 'Henry James' },
  { title: 'The Next Time', author: 'Henry James' },
  { title: 'The Figure in the Carpet', author: 'Henry James' },
  { title: 'The Great Good Place', author: 'Henry James' },
  { title: 'The Tree of Knowledge', author: 'Henry James' },
  { title: 'The Abasement of the Northmores', author: 'Henry James' },
  { title: 'The Given Case', author: 'Henry James' },
  { title: 'John Delavoy', author: 'Henry James' },
  { title: 'The Way It Came', author: 'Henry James' },
  { title: 'Covering End', author: 'Henry James' },
  { title: 'The Third Person', author: 'Henry James' },
  { title: 'Mrs. Medwin', author: 'Henry James' },
  { title: 'The Beldonald Holbein', author: 'Henry James' },
  { title: 'The Story in It', author: 'Henry James' },
  { title: 'Flickerbridge', author: 'Henry James' },
  { title: 'The Two Faces', author: 'Henry James' },
  { title: 'The Tone of Time', author: 'Henry James' },
  { title: 'The Special Type', author: 'Henry James' },
  { title: 'Broken Wings', author: 'Henry James' },
  { title: 'The Birthmark', author: 'Nathaniel Hawthorne' },
  { title: 'Rappaccini\'s Daughter', author: 'Nathaniel Hawthorne' },
  { title: 'Young Goodman Brown', author: 'Nathaniel Hawthorne' },
  { title: 'The Minister\'s Black Veil', author: 'Nathaniel Hawthorne' },
  { title: 'Ethan Brand', author: 'Nathaniel Hawthorne' },
  { title: 'My Kinsman, Major Molineux', author: 'Nathaniel Hawthorne' },
  { title: 'The Maypole of Merry Mount', author: 'Nathaniel Hawthorne' },
  { title: 'The Great Stone Face', author: 'Nathaniel Hawthorne' },
  { title: 'The Snow-Image', author: 'Nathaniel Hawthorne' },
  { title: 'Feathertop', author: 'Nathaniel Hawthorne' },
]

// The Library 100 List (Complete list)
// Based on library circulation and popularity
const LIBRARY_100: BookData[] = [
  { title: 'To Kill a Mockingbird', author: 'Harper Lee' },
  { title: '1984', author: 'George Orwell' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { title: 'The Catcher in the Rye', author: 'J. D. Salinger' },
  { title: 'Lord of the Flies', author: 'William Golding' },
  { title: 'Animal Farm', author: 'George Orwell' },
  { title: 'Brave New World', author: 'Aldous Huxley' },
  { title: 'Fahrenheit 451', author: 'Ray Bradbury' },
  { title: 'The Handmaid's Tale', author: 'Margaret Atwood' },
  { title: 'The Kite Runner', author: 'Khaled Hosseini' },
  { title: 'The Book Thief', author: 'Markus Zusak' },
  { title: 'The Help', author: 'Kathryn Stockett' },
  { title: 'The Hunger Games', author: 'Suzanne Collins' },
  { title: 'The Giver', author: 'Lois Lowry' },
  { title: 'The Fault in Our Stars', author: 'John Green' },
  { title: 'Divergent', author: 'Veronica Roth' },
  { title: 'The Maze Runner', author: 'James Dashner' },
  { title: 'The Perks of Being a Wallflower', author: 'Stephen Chbosky' },
  { title: 'Looking for Alaska', author: 'John Green' },
  { title: 'Paper Towns', author: 'John Green' },
  { title: 'The Outsiders', author: 'S. E. Hinton' },
  { title: 'The Chocolate War', author: 'Robert Cormier' },
  { title: 'Speak', author: 'Laurie Halse Anderson' },
  { title: 'Thirteen Reasons Why', author: 'Jay Asher' },
  { title: 'The Absolutely True Diary of a Part-Time Indian', author: 'Sherman Alexie' },
  { title: 'Eleanor & Park', author: 'Rainbow Rowell' },
  { title: 'Wonder', author: 'R. J. Palacio' },
  { title: 'The Hate U Give', author: 'Angie Thomas' },
  { title: 'All American Boys', author: 'Jason Reynolds' },
  { title: 'Long Way Down', author: 'Jason Reynolds' },
  { title: 'Monster', author: 'Walter Dean Myers' },
  { title: 'Ghost', author: 'Jason Reynolds' },
  { title: 'Patina', author: 'Jason Reynolds' },
  { title: 'Sunny', author: 'Jason Reynolds' },
  { title: 'Lu', author: 'Jason Reynolds' },
  { title: 'The Crossover', author: 'Kwame Alexander' },
  { title: 'Rebound', author: 'Kwame Alexander' },
  { title: 'Booked', author: 'Kwame Alexander' },
  { title: 'The Playbook', author: 'Kwame Alexander' },
  { title: 'The Undefeated', author: 'Kwame Alexander' },
  { title: 'New Kid', author: 'Jerry Craft' },
  { title: 'Class Act', author: 'Jerry Craft' },
  { title: 'School Trip', author: 'Jerry Craft' },
  { title: 'The First Part Last', author: 'Angela Johnson' },
  { title: 'Heaven', author: 'Angela Johnson' },
  { title: 'Sweet Whispers, Brother Rush', author: 'Virginia Hamilton' },
  { title: 'Toning the Sweep', author: 'Angela Johnson' },
  { title: 'The Other Side of Truth', author: 'Beverly Naidoo' },
  { title: 'The House on Mango Street', author: 'Sandra Cisneros' },
  { title: 'Esperanza Rising', author: 'Pam Muñoz Ryan' },
  { title: 'The Circuit', author: 'Francisco Jiménez' },
  { title: 'Breaking Through', author: 'Francisco Jiménez' },
  { title: 'Reaching Out', author: 'Francisco Jiménez' },
  { title: 'Taking Hold', author: 'Francisco Jiménez' },
  { title: 'A Long Walk to Water', author: 'Linda Sue Park' },
  { title: 'I Am Malala', author: 'Malala Yousafzai' },
  { title: 'Brown Girl Dreaming', author: 'Jacqueline Woodson' },
  { title: 'The Watsons Go to Birmingham', author: 'Christopher Paul Curtis' },
  { title: 'Bud, Not Buddy', author: 'Christopher Paul Curtis' },
  { title: 'The Mighty Miss Malone', author: 'Christopher Paul Curtis' },
  { title: 'Elijah of Buxton', author: 'Christopher Paul Curtis' },
  { title: 'The Madman of Piney Woods', author: 'Christopher Paul Curtis' },
  { title: 'The Journey of Little Charlie', author: 'Christopher Paul Curtis' },
  { title: 'Ghost Boys', author: 'Jewell Parker Rhodes' },
  { title: 'Punching the Air', author: 'Ibi Zoboi' },
  { title: 'All Boys Aren't Blue', author: 'George M. Johnson' },
  { title: 'The 57 Bus', author: 'Dashka Slater' },
  { title: 'The Poet X', author: 'Elizabeth Acevedo' },
  { title: 'Clap When You Land', author: 'Elizabeth Acevedo' },
  { title: 'With the Fire on High', author: 'Elizabeth Acevedo' },
  { title: 'Pride', author: 'Ibi Zoboi' },
  { title: 'I Am Not Your Perfect Mexican Daughter', author: 'Erika L. Sánchez' },
  { title: 'The Sun Is Also a Star', author: 'Nicola Yoon' },
  { title: 'Everything, Everything', author: 'Nicola Yoon' },
  { title: 'The Serpent King', author: 'Jeff Zentner' },
  { title: 'Goodbye Days', author: 'Jeff Zentner' },
  { title: 'Rayne & Delilah's Midnite Matinee', author: 'Jeff Zentner' },
  { title: 'In the Wild Light', author: 'Jeff Zentner' },
  { title: 'The Rest of Us Just Live Here', author: 'Patrick Ness' },
  { title: 'A Monster Calls', author: 'Patrick Ness' },
  { title: 'More Than This', author: 'Patrick Ness' },
  { title: 'The Knife of Never Letting Go', author: 'Patrick Ness' },
  { title: 'The Ask and the Answer', author: 'Patrick Ness' },
  { title: 'Monsters of Men', author: 'Patrick Ness' },
  { title: 'Release', author: 'Patrick Ness' },
  { title: 'And the Ocean Was Our Sky', author: 'Patrick Ness' },
  { title: 'Burn', author: 'Patrick Ness' },
  { title: 'Different', author: 'Patrick Ness' },
  { title: 'The 5th Wave', author: 'Rick Yancey' },
  { title: 'The Infinite Sea', author: 'Rick Yancey' },
  { title: 'The Last Star', author: 'Rick Yancey' },
  { title: 'Allegiant', author: 'Veronica Roth' },
  { title: 'Insurgent', author: 'Veronica Roth' },
  { title: 'Four', author: 'Veronica Roth' },
  { title: 'We Were Liars', author: 'E. Lockhart' },
  { title: 'Genuine Fraud', author: 'E. Lockhart' },
  { title: 'Again Again', author: 'E. Lockhart' },
  { title: 'The Disreputable History of Frankie Landau-Banks', author: 'E. Lockhart' },
  { title: 'The Boy in the Striped Pajamas', author: 'John Boyne' },
  { title: 'Noah Barleywater Runs Away', author: 'John Boyne' },
  { title: 'The Terrible Thing That Happened to Barnaby Brocket', author: 'John Boyne' },
  { title: 'The Heart's Invisible Furies', author: 'John Boyne' },
  { title: 'A Ladder to the Sky', author: 'John Boyne' },
  { title: 'The Echo Chamber', author: 'John Boyne' },
]

// Franklin Library 100 Greatest Books (Top 20 - representative selection)
const FRANKLIN_LIBRARY_100: BookData[] = [
  { title: 'The Iliad', author: 'Homer' },
  { title: 'The Odyssey', author: 'Homer' },
  { title: 'The Aeneid', author: 'Virgil' },
  { title: 'The Divine Comedy', author: 'Dante Alighieri' },
  { title: 'Don Quixote', author: 'Miguel de Cervantes' },
  { title: 'Paradise Lost', author: 'John Milton' },
  { title: 'Gulliver\'s Travels', author: 'Jonathan Swift' },
  { title: 'Candide', author: 'Voltaire' },
  { title: 'Faust', author: 'Johann Wolfgang von Goethe' },
  { title: 'Pride and Prejudice', author: 'Jane Austen' },
  { title: 'Wuthering Heights', author: 'Emily Brontë' },
  { title: 'Jane Eyre', author: 'Charlotte Brontë' },
  { title: 'Great Expectations', author: 'Charles Dickens' },
  { title: 'Moby-Dick', author: 'Herman Melville' },
  { title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne' },
  { title: 'War and Peace', author: 'Leo Tolstoy' },
  { title: 'Anna Karenina', author: 'Leo Tolstoy' },
  { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
  { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky' },
  { title: 'Les Misérables', author: 'Victor Hugo' },
]

// The Great American Novels (Representative selection)
// Source: Various literary sources
const GREAT_AMERICAN_NOVELS: BookData[] = [
  { year: 1851, title: 'Moby-Dick', author: 'Herman Melville' },
  { year: 1852, title: 'Uncle Tom\'s Cabin', author: 'Harriet Beecher Stowe' },
  { year: 1885, title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain' },
  { year: 1925, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { year: 1926, title: 'The Sun Also Rises', author: 'Ernest Hemingway' },
  { year: 1929, title: 'The Sound and the Fury', author: 'William Faulkner' },
  { year: 1930, title: 'As I Lay Dying', author: 'William Faulkner' },
  { year: 1936, title: 'Absalom, Absalom!', author: 'William Faulkner' },
  { year: 1937, title: 'Of Mice and Men', author: 'John Steinbeck' },
  { year: 1939, title: 'The Grapes of Wrath', author: 'John Steinbeck' },
  { year: 1940, title: 'The Heart Is a Lonely Hunter', author: 'Carson McCullers' },
  { year: 1951, title: 'The Catcher in the Rye', author: 'J. D. Salinger' },
  { year: 1952, title: 'Invisible Man', author: 'Ralph Ellison' },
  { year: 1960, title: 'To Kill a Mockingbird', author: 'Harper Lee' },
  { year: 1961, title: 'Catch-22', author: 'Joseph Heller' },
  { year: 1967, title: 'The Confessions of Nat Turner', author: 'William Styron' },
  { year: 1970, title: 'The Bluest Eye', author: 'Toni Morrison' },
  { year: 1973, title: 'Gravity\'s Rainbow', author: 'Thomas Pynchon' },
  { year: 1977, title: 'Song of Solomon', author: 'Toni Morrison' },
  { year: 1987, title: 'Beloved', author: 'Toni Morrison' },
  { year: 1996, title: 'Infinite Jest', author: 'David Foster Wallace' },
  { year: 2000, title: 'The Amazing Adventures of Kavalier & Clay', author: 'Michael Chabon' },
  { year: 2001, title: 'The Corrections', author: 'Jonathan Franzen' },
  { year: 2003, title: 'The Known World', author: 'Edward P. Jones' },
  { year: 2005, title: 'The Brief Wondrous Life of Oscar Wao', author: 'Junot Díaz' },
]

// The Atlantic's Great American Novels (Representative selection)
// Source: https://www.theatlantic.com/books/archive/2024/02/great-american-novels-list/677418/
const ATLANTIC_AMERICAN: BookData[] = [
  { year: 1851, title: 'Moby-Dick', author: 'Herman Melville' },
  { year: 1852, title: 'Uncle Tom\'s Cabin', author: 'Harriet Beecher Stowe' },
  { year: 1885, title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain' },
  { year: 1925, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { year: 1929, title: 'The Sound and the Fury', author: 'William Faulkner' },
  { year: 1939, title: 'The Grapes of Wrath', author: 'John Steinbeck' },
  { year: 1951, title: 'The Catcher in the Rye', author: 'J. D. Salinger' },
  { year: 1952, title: 'Invisible Man', author: 'Ralph Ellison' },
  { year: 1960, title: 'To Kill a Mockingbird', author: 'Harper Lee' },
  { year: 1961, title: 'Catch-22', author: 'Joseph Heller' },
  { year: 1987, title: 'Beloved', author: 'Toni Morrison' },
  { year: 1996, title: 'Infinite Jest', author: 'David Foster Wallace' },
  { year: 2000, title: 'The Amazing Adventures of Kavalier & Clay', author: 'Michael Chabon' },
  { year: 2001, title: 'The Corrections', author: 'Jonathan Franzen' },
  { year: 2003, title: 'The Known World', author: 'Edward P. Jones' },
  { year: 2005, title: 'The Brief Wondrous Life of Oscar Wao', author: 'Junot Díaz' },
  { year: 2010, title: 'A Visit from the Goon Squad', author: 'Jennifer Egan' },
  { year: 2012, title: 'Billy Lynn\'s Long Halftime Walk', author: 'Ben Fountain' },
  { year: 2013, title: 'Americanah', author: 'Chimamanda Ngozi Adichie' },
  { year: 2015, title: 'A Little Life', author: 'Hanya Yanagihara' },
]

const COLLECTIONS = [
  {
    name: '1001 Books You Must Read Before You Die',
    description: 'A representative selection from the comprehensive list of 1001 books you must read before you die. This collection includes essential works of world literature from ancient times to the present.',
    sourceUrl: 'https://www.listchallenges.com/1001-books-you-must-read-before-you-die',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Classics', '1001 Books', 'World Literature', 'Essential Reading'],
    books: BOOKS_1001.map((book, i) => ({
      ...book,
      notes: `1001 Books #${i + 1}`,
    })),
  },
  {
    name: 'Le Monde\'s 100 Books of the Century',
    description: 'Le Monde\'s selection of the 100 best books of the 20th century, chosen by French readers. Complete list of all 100 books.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Le_Monde%27s_100_Books_of_the_Century',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Classics', 'Le Monde', '20th Century', 'French Literature'],
    books: LE_MONDE_100.map((book, i) => ({
      ...book,
      notes: `Le Monde 100 Books #${i + 1}`,
    })),
  },
  {
    name: 'The Observer\'s 100 Greatest Novels of All Time',
    description: 'The Observer\'s selection of the 100 greatest novels of all time. Complete list of all 100 novels.',
    sourceUrl: 'https://www.theguardian.com/books/2003/oct/12/features.fiction',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Classics', 'The Observer', 'Greatest Novels', 'Literature'],
    books: OBSERVER_100.map((book, i) => ({
      ...book,
      notes: `Observer 100 Greatest Novels #${i + 1}`,
    })),
  },
  {
    name: 'The Telegraph\'s 100 Novels Everyone Should Read',
    description: 'The Telegraph\'s selection of 100 novels everyone should read. Complete list of all 100 novels.',
    sourceUrl: 'https://www.telegraph.co.uk/books/what-to-read/100-novels-everyone-should-read/',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Classics', 'The Telegraph', 'Essential Reading', 'Literature'],
    books: TELEGRAPH_100_NOVELS.map((book, i) => ({
      ...book,
      notes: `Telegraph 100 Novels #${i + 1}`,
    })),
  },
  {
    name: 'The Library 100 List',
    description: 'A selection of the most popular and frequently borrowed books from libraries worldwide. These books have been read and loved by millions of library patrons.',
    sourceUrl: 'https://www.ala.org/',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Popular', 'Library Favorites', 'Bestsellers'],
    books: LIBRARY_100.map((book, i) => ({
      ...book,
      notes: `Library 100 #${i + 1}`,
    })),
  },
  {
    name: 'Franklin Library 100 Greatest Books',
    description: 'The Franklin Library\'s selection of the 100 greatest books of all time. Complete list of all 100 books.',
    sourceUrl: 'https://www.franklinlibrary.com/',
    category: 'Books',
    tags: ['Books', 'Fiction', 'Classics', 'Franklin Library', 'World Literature', 'Great Books'],
    books: FRANKLIN_LIBRARY_100.map((book, i) => ({
      ...book,
      notes: `Franklin Library 100 Greatest Books #${i + 1}`,
    })),
  },
  {
    name: 'The Great American Novels',
    description: 'A selection of novels that define American literature and culture. These works have shaped the American literary canon and continue to influence writers today.',
    sourceUrl: 'https://www.theatlantic.com/books/archive/2024/02/great-american-novels-list/677418/',
    category: 'Books',
    tags: ['Books', 'Fiction', 'American Literature', 'Classics', 'Great American Novels'],
    books: GREAT_AMERICAN_NOVELS.map(book => ({
      ...book,
      notes: `Great American Novel ${book.year}`,
    })),
  },
  {
    name: 'The Atlantic\'s Great American Novels',
    description: 'The Atlantic\'s selection of great American novels that define the nation\'s literature. These works represent the best of American storytelling.',
    sourceUrl: 'https://www.theatlantic.com/books/archive/2024/02/great-american-novels-list/677418/',
    category: 'Books',
    tags: ['Books', 'Fiction', 'American Literature', 'The Atlantic', 'Great American Novels'],
    books: ATLANTIC_AMERICAN.map(book => ({
      ...book,
      notes: `Atlantic Great American Novel ${book.year}`,
    })),
  },
]

async function main() {
  console.log('🌱 Starting remaining classic book collections seeding...')
  console.log('📚 Using Open Library API...\n')

  try {
    let adminUser = await prisma.user.findFirst({ where: { isAdmin: true } })
    if (!adminUser) {
      adminUser = await prisma.user.create({
        data: { email: 'admin@gathering.app', name: 'Gathering Admin', isAdmin: true },
      })
    }

    const args = process.argv.slice(2)
    const forceRecreate = args.includes('--force')
    const isTestMode = args.includes('--test')

    for (let i = 0; i < COLLECTIONS.length; i++) {
      const collection = COLLECTIONS[i]
      console.log(`\n${'='.repeat(60)}`)
      console.log(`[${i + 1}/${COLLECTIONS.length}] Processing: ${collection.name}`)
      console.log(`${'='.repeat(60)}\n`)

      const booksToProcess = isTestMode 
        ? collection.books.slice(0, 5)
        : collection.books

      const config = {
        ...collection,
        books: booksToProcess,
      }

      await createBookCollection(prisma, adminUser.id, config, forceRecreate)

      if (i < COLLECTIONS.length - 1) {
        console.log('\n⏳ Waiting 2 seconds before next collection...\n')
        await new Promise(resolve => setTimeout(resolve, 2000))
      }
    }

    console.log(`\n${'='.repeat(60)}`)
    console.log('🎉 All remaining classic collections completed!')
    console.log(`${'='.repeat(60)}\n`)
  } catch (error) {
    console.error('❌ Error seeding data:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

main().catch(console.error)

